services:
    db:
      image: postgres
      container_name: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: root
      ports:
        - 5433:5433
        
    app:
      depends_on:
          - db
      build:
        context: .
        dockerfile: Dockerfile
      image: application
      container_name: application
      ports:
        - 8080:8080
      hostname: application

